#!/usr/bin/env bash
# Author: Enan Ajmain
# Email : 3nan.ajmain@gmail.com
# Github: https://github.com/enanajmain

# A script for recording screencast

A="$(pacmd list-sources | grep -PB 1 "analog.*monitor>" | head -n 1 | perl -pe 's/.* //g')"
F="/home/enan/Videos/$(date --iso-8601=minutes | perl -pe 's/[^0-9]+//g').mkv"
V="$(xdpyinfo | grep dimensions | perl -pe 's/.* ([0-9]+x[0-9]+) .*/$1/g')"

ffmpeg -video_size "$V" -framerate 30 -f x11grab -i :0.0 -f alsa -i default \
	-c:v libx264 -c:a flac "$F"
